// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADfQ_WmWvTIdqJvg-5P6DPgIuD_tq0o6Y',
    appId: '1:693806636421:web:a80b1c47a32a510c5738ec',
    messagingSenderId: '693806636421',
    projectId: 'profile-54a68',
    authDomain: 'profile-54a68.firebaseapp.com',
    storageBucket: 'profile-54a68.firebasestorage.app',
    measurementId: 'G-KP123S3KLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVgKo9B9qERa33opVKYqUs6hVD0TxVhnk',
    appId: '1:693806636421:android:ccc849fe6f3456bc5738ec',
    messagingSenderId: '693806636421',
    projectId: 'profile-54a68',
    storageBucket: 'profile-54a68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGQNrBOJE_jHl7OBDwkBFnbXFYa73SpF4',
    appId: '1:693806636421:ios:1fc1e03a57672ce95738ec',
    messagingSenderId: '693806636421',
    projectId: 'profile-54a68',
    storageBucket: 'profile-54a68.firebasestorage.app',
    iosBundleId: 'com.example.teamCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGQNrBOJE_jHl7OBDwkBFnbXFYa73SpF4',
    appId: '1:693806636421:ios:1fc1e03a57672ce95738ec',
    messagingSenderId: '693806636421',
    projectId: 'profile-54a68',
    storageBucket: 'profile-54a68.firebasestorage.app',
    iosBundleId: 'com.example.teamCourse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADfQ_WmWvTIdqJvg-5P6DPgIuD_tq0o6Y',
    appId: '1:693806636421:web:5a5d60f3bfca3d1b5738ec',
    messagingSenderId: '693806636421',
    projectId: 'profile-54a68',
    authDomain: 'profile-54a68.firebaseapp.com',
    storageBucket: 'profile-54a68.firebasestorage.app',
    measurementId: 'G-SV3D1L9QPH',
  );
}
